apiVersion: v1
kind: Service
metadata:
  labels:
    app: scaleio-metrics
  name: scaleio-metrics
  namespace: kube-system
spec:
  ports:
    - port: 80
      protocol: TCP
  clusterIP: None
  selector:
    app: scaleio-metrics
